services:
  hiringbellAPI:
    image: api_hiringbell
    network_mode: bridge
    environment:
      -  TZ=Asia/Kolkata
      -  DEBIAN_FRONTENT=noninteractive
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  5000:80