services:
  hiringbellAPI:
    image: api_hiringbell
    network_mode: bridge
    environment:
      -  TZ=Asia/Kolkata
      -  DEBIAN_FRONTENT=noninteractive
    build:
      context: .
      dockerfile: OnlineDataBuilder/Dockerfile
    ports:
      -  5000:80
    volumes:
      -  /home/ik/workspace/Documents:/app/Documents
      -  /home/ik/workspace/Documents/appsettings.json:/app/appsettings.json
